// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckServices():Promise<main.ServiceStatus>;

export function GetStatus():Promise<string>;

export function GetVersion():Promise<string>;

export function StartServices():Promise<string>;
