// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckServices() {
  return window['go']['main']['App']['CheckServices']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function StartServices() {
  return window['go']['main']['App']['StartServices']();
}
