#ifndef NEXUS_VECTOR_H
#define NEXUS_VECTOR_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdint.h>
#include <stddef.h>

/**
 * 计算两个 f32 向量的余弦相似度。
 *
 * 返回 [-1.0, 1.0]，若任一向量为零向量则返回 0.0。
 */
float nexus_cosine_similarity(const float *a, const float *b, size_t len);

/**
 * 批量计算 query 与 docs 矩阵中每行的余弦相似度。
 *
 * - `query`: 长度为 `dim` 的向量
 * - `docs`: `n_docs × dim` 的行主序矩阵
 * - `out`: 长度为 `n_docs` 的输出缓冲区
 *
 * 返回 0 表示成功，-1 表示参数错误。
 */
int nexus_batch_cosine(const float *query,
                       const float *docs,
                       size_t dim,
                       size_t n_docs,
                       float *out);

#endif  /* NEXUS_VECTOR_H */
