#ifndef NEXUS_CRYPTO_H
#define NEXUS_CRYPTO_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdint.h>
#include <stddef.h>

/**
 * AES-256-GCM 加密。
 *
 * - `key`: 32 字节密钥
 * - `plaintext` / `pt_len`: 明文
 * - `out_buf` / `out_cap`: 输出缓冲区（需 >= pt_len + 12 + 16）
 * - `out_len`: 实际写入长度（nonce 12B + ciphertext + tag 16B）
 *
 * 返回 0 成功，-1 失败。
 */
int nexus_aes256gcm_encrypt(const unsigned char *key,
                            const unsigned char *plaintext,
                            size_t pt_len,
                            unsigned char *out_buf,
                            size_t out_cap,
                            size_t *out_len);

/**
 * AES-256-GCM 解密。
 *
 * - `data` / `data_len`: nonce(12B) + ciphertext + tag(16B)
 * - `out_buf` / `out_cap`: 明文输出缓冲区
 * - `out_len`: 实际明文长度
 */
int nexus_aes256gcm_decrypt(const unsigned char *key,
                            const unsigned char *data,
                            size_t data_len,
                            unsigned char *out_buf,
                            size_t out_cap,
                            size_t *out_len);

/**
 * bcrypt 哈希。返回 C 字符串，调用方用 nexus_crypto_free 释放。
 */
char *nexus_bcrypt_hash(const char *password, int cost);

/**
 * bcrypt 验证。返回 1 匹配，0 不匹配，-1 错误。
 */
int nexus_bcrypt_verify(const char *password, const char *hash);

/**
 * 释放 nexus_bcrypt_hash 返回的内存。
 */
void nexus_crypto_free(char *ptr);

#endif  /* NEXUS_CRYPTO_H */
