/* Auto-generated by cbindgen. Do not edit. */

#ifndef NEXUS_GRAPH_H
#define NEXUS_GRAPH_H

#include <stdint.h>
#include <stddef.h>

int nexus_page_rank(const uint32_t *edges,
                    size_t n_edges,
                    size_t n_nodes,
                    float damping,
                    size_t iterations,
                    float *out);

int nexus_label_propagation(const uint32_t *edges,
                            size_t n_edges,
                            size_t n_nodes,
                            size_t max_iter,
                            uint32_t *out);

int nexus_shortest_path(const uint32_t *edges,
                        size_t n_edges,
                        size_t n_nodes,
                        uint32_t from,
                        uint32_t to,
                        uint32_t *out_path,
                        size_t *out_len);

#endif /* NEXUS_GRAPH_H */
