#ifndef NEXUS_DECAY_H
#define NEXUS_DECAY_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdint.h>
#include <stddef.h>

/**
 * 批量记忆衰减参数（C 侧结构体）。
 */
typedef struct DecayInput {
  double base_importance;
  double decay_factor;
  double days_since_access;
  int access_count;
} DecayInput;

/**
 * 计算单条记忆的有效重要性。
 *
 * 公式：effective = base × decay_factor × exp(-ln2 × days / 30) × (1 + ln(1+access) × 0.1)
 * 结果 clamp 到 [MIN_DECAY, 1.0]。
 */
double nexus_decay(double base_importance,
                   double decay_factor,
                   double days_since_access,
                   int access_count);

/**
 * 批量计算衰减。
 *
 * - `inputs`: 长度为 `count` 的 DecayInput 数组
 * - `out`: 长度为 `count` 的输出缓冲区
 *
 * 返回 0 成功，-1 参数错误。
 */
int nexus_batch_decay(const struct DecayInput *inputs, size_t count, double *out);

#endif  /* NEXUS_DECAY_H */
