#ifndef NEXUS_TOKENIZER_H
#define NEXUS_TOKENIZER_H

/* Auto-generated by cbindgen. Do not edit. */

#include <stdint.h>
#include <stdlib.h>

/**
 * 对输入文本进行中文分词。
 *
 * 返回一个以 `\0` 分隔、以 `\0\0` 终结的 C 字符串。
 * 调用方必须使用 `nexus_tokenizer_free` 释放内存。
 */
char *nexus_tokenize(const char *text, unsigned int *out_count);

/**
 * 释放 `nexus_tokenize` 返回的内存。
 */
void nexus_tokenizer_free(char *ptr);

/**
 * 设置 IDF 表。entries 格式: "word1\0idf1\0word2\0idf2\0"。
 * doc_count 为文档总数 N。返回 0 成功，-1 失败。
 */
int nexus_set_idf_table(const char *entries, unsigned int entries_len, double doc_count);

/**
 * 计算 query 与 document 之间的 BM25 得分。
 *
 * k1 = 1.2, b = 0.75, avg_dl 由调用方提供。
 */
double nexus_bm25_score(const char *query, const char *doc, double avg_dl);

#endif  /* NEXUS_TOKENIZER_H */
